module subAssign( data_operandB, isSub, modifiedB);
    input [31:0] data_operandB;
    input isSub;
    output [31:0] modifiedB;
    xor (modifiedB[0], data_operandB[0], isSub);
    xor (modifiedB[1], data_operandB[1], isSub);
    xor (modifiedB[2], data_operandB[2],isSub);
    xor (modifiedB[3], data_operandB[3],isSub);
    xor (modifiedB[4], data_operandB[4],isSub);
    xor (modifiedB[5], data_operandB[5],isSub);
    xor (modifiedB[6], data_operandB[6],isSub);
    xor (modifiedB[7], data_operandB[7], isSub);
    xor (modifiedB[8], data_operandB[8], isSub);
    xor (modifiedB[9], data_operandB[9],isSub);
    xor (modifiedB[10],data_operandB[10],isSub);
    xor (modifiedB[11], data_operandB[11],isSub);
    xor (modifiedB[12], data_operandB[12],isSub);
    xor (modifiedB[13], data_operandB[13],isSub);
    xor (modifiedB[14], data_operandB[14],isSub);
    xor (modifiedB[15], data_operandB[15],isSub);
    xor (modifiedB[16], data_operandB[16],isSub);
    xor (modifiedB[17], data_operandB[17],isSub);
    xor (modifiedB[18], data_operandB[18],isSub);
    xor (modifiedB[19], data_operandB[19],isSub);
    xor (modifiedB[20], data_operandB[20],isSub);
    xor (modifiedB[21], data_operandB[21],isSub);
    xor (modifiedB[22], data_operandB[22],isSub);
    xor (modifiedB[23], data_operandB[23], isSub);
    xor (modifiedB[24], data_operandB[24], isSub);
    xor (modifiedB[25], data_operandB[25], isSub);
    xor (modifiedB[26], data_operandB[26], isSub);
    xor (modifiedB[27], data_operandB[27], isSub);
    xor (modifiedB[28], data_operandB[28], isSub);
    xor (modifiedB[29], data_operandB[29], isSub);
    xor (modifiedB[30], data_operandB[30], isSub);
    xor (modifiedB[31], data_operandB[31], isSub);
endmodule