module writeEnables(writePortDecoderOutput, ctrl_writeEnable, we);
    input [31:0] writePortDecoderOutput;
    input ctrl_writeEnable;
    output [31:0] we;
    and (we[0], writePortDecoderOutput[0], ctrl_writeEnable);
    and (we[1], writePortDecoderOutput[1], ctrl_writeEnable);
    and (we[2], writePortDecoderOutput[2], ctrl_writeEnable);
    and (we[3], writePortDecoderOutput[3], ctrl_writeEnable);
    and (we[4], writePortDecoderOutput[4], ctrl_writeEnable);
    and (we[5], writePortDecoderOutput[5], ctrl_writeEnable);
    and (we[6], writePortDecoderOutput[6], ctrl_writeEnable);
    and (we[7], writePortDecoderOutput[7], ctrl_writeEnable);
    and (we[8], writePortDecoderOutput[8], ctrl_writeEnable);
    and (we[9], writePortDecoderOutput[9], ctrl_writeEnable);
    and (we[10], writePortDecoderOutput[10], ctrl_writeEnable);
    and (we[11], writePortDecoderOutput[11], ctrl_writeEnable);
    and (we[12], writePortDecoderOutput[12], ctrl_writeEnable);
    and (we[13], writePortDecoderOutput[13], ctrl_writeEnable);
    and (we[14], writePortDecoderOutput[14], ctrl_writeEnable);
    and (we[15], writePortDecoderOutput[15], ctrl_writeEnable);
    and (we[16], writePortDecoderOutput[16], ctrl_writeEnable);
    and (we[17], writePortDecoderOutput[17], ctrl_writeEnable);
    and (we[18], writePortDecoderOutput[18], ctrl_writeEnable);
    and (we[19], writePortDecoderOutput[19], ctrl_writeEnable);
    and (we[20], writePortDecoderOutput[20], ctrl_writeEnable);
    and (we[21], writePortDecoderOutput[21], ctrl_writeEnable);
    and (we[22], writePortDecoderOutput[22], ctrl_writeEnable);
    and (we[23], writePortDecoderOutput[23], ctrl_writeEnable);
    and (we[24], writePortDecoderOutput[24], ctrl_writeEnable);
    and (we[25], writePortDecoderOutput[25], ctrl_writeEnable);
    and (we[26], writePortDecoderOutput[26], ctrl_writeEnable);
    and (we[27], writePortDecoderOutput[27], ctrl_writeEnable);
    and (we[28], writePortDecoderOutput[28], ctrl_writeEnable);
    and (we[29], writePortDecoderOutput[29], ctrl_writeEnable);
    and (we[30], writePortDecoderOutput[30], ctrl_writeEnable);
    and (we[31], writePortDecoderOutput[31], ctrl_writeEnable);
endmodule