module divRegister64(clk, in, out, clrn, we);//d, clk, clrn, prn, in_enable, out_enable, out
    input [63:0] in;
    output [63:0] out;
    input clk, we, clrn;
    wire ena, zero;
    assign zero = 1'b0;
    assign ena = we;
    dffe_ref d0 (.q(out[0]), .d(in[0]), .clk(clk), .en(ena), .clr(clrn));//q, d, clk, en, clr)
    dffe_ref d1 (.q(out[1]), .d(in[1]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d2 (.q(out[2]), .d(in[2]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d3 (.q(out[3]), .d(in[3]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d4 (.q(out[4]), .d(in[4]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d5 (.q(out[5]), .d(in[5]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d6 (.q(out[6]), .d(in[6]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d7 (.q(out[7]), .d(in[7]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d8 (.q(out[8]), .d(in[8]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d9 (.q(out[9]), .d(in[9]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d10 (.q(out[10]), .d(in[10]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d11 (.q(out[11]), .d(in[11]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d12 (.q(out[12]), .d(in[12]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d13 (.q(out[13]), .d(in[13]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d14 (.q(out[14]), .d(in[14]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d15 (.q(out[15]), .d(in[15]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d16 (.q(out[16]), .d(in[16]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d17 (.q(out[17]), .d(in[17]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d18 (.q(out[18]), .d(in[18]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d19 (.q(out[19]), .d(in[19]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d20 (.q(out[20]), .d(in[20]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d21 (.q(out[21]), .d(in[21]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d22 (.q(out[22]), .d(in[22]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d23 (.q(out[23]), .d(in[23]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d24 (.q(out[24]), .d(in[24]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d25 (.q(out[25]), .d(in[25]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d26 (.q(out[26]), .d(in[26]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d27 (.q(out[27]), .d(in[27]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d28 (.q(out[28]), .d(in[28]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d29 (.q(out[29]), .d(in[29]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d30 (.q(out[30]), .d(in[30]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d31 (.q(out[31]), .d(in[31]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d32 (.q(out[32]), .d(in[32]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d33 (.q(out[33]), .d(in[33]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d34 (.q(out[34]), .d(in[34]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d35 (.q(out[35]), .d(in[35]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d36 (.q(out[36]), .d(in[36]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d37 (.q(out[37]), .d(in[37]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d38 (.q(out[38]), .d(in[38]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d39 (.q(out[39]), .d(in[39]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d40 (.q(out[40]), .d(in[40]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d41 (.q(out[41]), .d(in[41]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d42 (.q(out[42]), .d(in[42]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d43 (.q(out[43]), .d(in[43]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d44 (.q(out[44]), .d(in[44]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d45 (.q(out[45]), .d(in[45]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d46 (.q(out[46]), .d(in[46]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d47 (.q(out[47]), .d(in[47]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d48 (.q(out[48]), .d(in[48]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d49 (.q(out[49]), .d(in[49]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d50 (.q(out[50]), .d(in[50]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d51 (.q(out[51]), .d(in[51]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d52 (.q(out[52]), .d(in[52]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d53 (.q(out[53]), .d(in[53]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d54 (.q(out[54]), .d(in[54]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d55 (.q(out[55]), .d(in[55]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d56 (.q(out[56]), .d(in[56]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d57 (.q(out[57]), .d(in[57]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d58 (.q(out[58]), .d(in[58]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d59 (.q(out[59]), .d(in[59]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d60 (.q(out[60]), .d(in[60]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d61 (.q(out[61]), .d(in[61]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d62 (.q(out[62]), .d(in[62]), .clk(clk), .en(ena), .clr(clrn));
    dffe_ref d63 (.q(out[63]), .d(in[63]), .clk(clk), .en(ena), .clr(clrn));
endmodule